{
 "title": "Zipkin Monitor",
 "description": "Visualize Prometheus metrics exported by OpenZipkin (http://zipkin.io/).",
 "tags": [
  "zipkin",
  "tracing"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Zipkin instances",
    "query": "label_values(http_server_requests_seconds_bucket{job=\"zipkin\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages received per transport",
   "type": "graph",
   "description": "Messages on left axis, Spans on right axis",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "messages per second" }
   ],
   "targets": [
    {
     "expr": "sum by(transport)(rate(zipkin_collector_messages_total{job=\"zipkin\",instance=~\"$instances\"}[$__interval]))\n",
     "legendFormat": "{{transport}} messages"
    }
   ]
  },
  {
   "title": "Spans received per transport",
   "type": "graph",
   "description": "Messages on left axis, Spans on right axis",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "spans per second" }
   ],
   "targets": [
    {
     "expr": "sum by(transport)(rate(zipkin_collector_spans_total{instance=~\"$instances\"}[$__interval]))\n",
     "legendFormat": "{{transport}} spans"
    }
   ]
  },
  {
   "title": "Dropped messages",
   "type": "graph",
   "description": "The number of messages dropped (for kafka, scribe and http)",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "dropped messages per second" }
   ],
   "targets": [
    {
     "expr": "sum by(transport)(rate(zipkin_collector_messages_dropped_total{job=\"zipkin\",instance=~\"$instances\"}[$__interval]))",
     "legendFormat": "{{transport}} dropped messages"
    }
   ]
  },
  {
   "title": "Spans dropped",
   "type": "graph",
   "description": "The number of spans dropped (for scribe, http and kafka)",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "dropped spans per second" }
   ],
   "targets": [
    {
     "expr": "sum by(transport)(rate(zipkin_collector_spans_dropped_total{instance=~\"$instances\"}[$__interval]))\n",
     "legendFormat": "{{transport}} dropped spans"
    }
   ]
  },
  {
   "title": "Bytes received per transport",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "sum by (transport)(rate(zipkin_collector_bytes_total{job=\"zipkin\",instance=~\"$instances\"}[$__interval]))",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(area,instance)(jvm_memory_used_bytes{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{instance}} {{area}} used"
    },
    {
     "expr": "sum by(area,instance)(jvm_memory_max_bytes{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{instance}} {{area}} max"
    },
    {
     "expr": "sum by(instance,id)(jvm_buffer_total_capacity_bytes{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{id}} max"
    }
   ]
  },
  {
   "title": "System CPUs used, Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_count{job=\"zipkin\",instance=~\"$instances\"}",
     "legendFormat": "{{instance}} CPUs"
    },
    {
     "expr": "system_load_average_1m{job=\"zipkin\",instance=~\"$instances\"}",
     "legendFormat": "{{instance}} load"
    }
   ]
  },
  {
   "title": "JVM Classes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{job=\"zipkin\",instance=~\"$instances\"}",
     "legendFormat": "{{instance}} current"
    },
    {
     "expr": "jvm_classes_unloaded_classes_total{job=\"zipkin\",instance=~\"$instances\"}",
     "legendFormat": "{{instance}} unloaded since boot"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(jvm_threads_live_threads{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": " {{instance}} live"
    },
    {
     "expr": "sum by(instance)(jvm_threads_daemon_threads{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{instance}} daemon"
    },
    {
     "expr": "sum by(instance)(jvm_threads_peak_threads{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{instance}} peak"
    },
    {
     "expr": "sum by(instance)(jvm_threads_states_threads{job=\"zipkin\",instance=~\"$instances\"})",
     "legendFormat": "{{instance}}-{{state}}"
    }
   ]
  }
 ]
}